spring:
  profiles:
    active: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/rider_service_db
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  flyway:
#    baseline-on-migrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  kafka:
    bootstrap:
      servers: localhost:9092,localhost:9093
    consumer:
      group-id: console-consumer-39158

server:
  port: 1620
