spring:
#  cloud:
#    config:
#      uri: http://localhost:8888
#spring:
#  config:
#    import:
#      optional:configserver:http://localhost:8880

  datasource:
    url: jdbc:mysql://localhost:3306/order_service_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
  kafka:
    bootstrapAddress: localhost:9092,localhost:9093
    consumer:
      group-id: console-consumer-39158
    bootstrap:
      servers: localhost:9092,localhost:9093
#  main:
#    allow-bean-definition-overriding: true
  main:
    allow-bean-definition-overriding: true
server:
  port: 1616
